### ISSUE TITLE
Bug when jQuery is loaded

### ISSUE THREAD

**Issue by parzibyte** [Templarian/ui.bootstrap.contextMenu#96]
When jQuery is loaded the menu is not hidding

**Comment by josetaira** [comment]
@parzibyte what jQuery version are you using? Could you maybe set up a plunker to show this?

**Comment by josetaira** [comment]
@parzibyte I just pushed in d8ca2d4, which was fixing a different bug but that should also fix this issue as well. Try it out and see if it works.

@Templarian we might need a new bower build sometime soon

**Comment by Templarian** [comment]
@josetaira Will plan to do one this week to get it out. Thanks for the heads up.

**Comment by parzibyte** [comment]
The bug is still present, but now i made a plunker. Here is the link: https://embed.plnkr.co/HSnNgLXEFBcRgoj8lGMn/

**Comment by josetaira** [comment]
hi @parzibyte could you just recheck this again with the latest commit? I wasn't directly fixing this, but just checking if that might have been the same problem as #98

**Comment by gauravpatni123** [comment]
how to add mouse over  in the contextmenu.js file?

**Comment by josetaira** [comment]
Closing this due to inactivity. If it's still an issue, just reopen it or create a new ticket @parzibyte
